/*
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_dv.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAdvlScopeProvider extends DelegatingScopeProvider {
}
