/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.accordant_dv


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AdvlStandaloneSetup extends AdvlStandaloneSetupGenerated {

	def static void doSetup() {
		new AdvlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
