/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.accordant_fv.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AfvlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co/edu/uniandes/accordant_fv/parser/antlr/internal/InternalAfvl.tokens");
	}
}
