/*
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_fv.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.accordant.fv.ui.internal.FvActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AfvlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FvActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FvActivator activator = FvActivator.getInstance();
		return activator != null ? activator.getInjector(FvActivator.CO_EDU_UNIANDES_ACCORDANT_FV_AFVL) : null;
	}

}
