/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.accordant_fv.ui;
 
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.accordant.fv.ui.internal.FvActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AfvlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FvActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FvActivator.getInstance().getInjector(FvActivator.CO_EDU_UNIANDES_ACCORDANT_FV_AFVL);
	}
	
}
