/*
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_fv.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.accordant.fv.ui.internal.FvActivator;

public class AfvlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FvActivator.getInstance().getInjector("co.edu.uniandes.accordant_fv.Afvl");
	}

}
