/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.accordant_rq.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AinlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class InputPackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.InputPackage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInputPackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInputPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cScenariosKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cScenariosAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cScenariosQScenarioParserRuleCall_6_0 = (RuleCall)cScenariosAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cScenariosAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cScenariosQScenarioParserRuleCall_7_1_0 = (RuleCall)cScenariosAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cTacticsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cGtacticsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cGtacticsTacticParserRuleCall_11_0 = (RuleCall)cGtacticsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cGtacticsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cGtacticsTacticParserRuleCall_12_1_0 = (RuleCall)cGtacticsAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//InputPackage:
		//	{InputPackage}
		//	'InputPackage'
		//	name=EString
		//	'{'
		//	'scenarios' '{' scenarios+=QScenario ("," scenarios+=QScenario)* '}'
		//	'tactics' '{' gtactics+=Tactic (',' gtactics+=Tactic)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{InputPackage} 'InputPackage' name=EString '{' 'scenarios' '{' scenarios+=QScenario ("," scenarios+=QScenario)* '}'
		//'tactics' '{' gtactics+=Tactic (',' gtactics+=Tactic)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//{InputPackage}
		public Action getInputPackageAction_0() { return cInputPackageAction_0; }
		
		//'InputPackage'
		public Keyword getInputPackageKeyword_1() { return cInputPackageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'scenarios'
		public Keyword getScenariosKeyword_4() { return cScenariosKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//scenarios+=QScenario
		public Assignment getScenariosAssignment_6() { return cScenariosAssignment_6; }
		
		//QScenario
		public RuleCall getScenariosQScenarioParserRuleCall_6_0() { return cScenariosQScenarioParserRuleCall_6_0; }
		
		//("," scenarios+=QScenario)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//scenarios+=QScenario
		public Assignment getScenariosAssignment_7_1() { return cScenariosAssignment_7_1; }
		
		//QScenario
		public RuleCall getScenariosQScenarioParserRuleCall_7_1_0() { return cScenariosQScenarioParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'tactics'
		public Keyword getTacticsKeyword_9() { return cTacticsKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//gtactics+=Tactic
		public Assignment getGtacticsAssignment_11() { return cGtacticsAssignment_11; }
		
		//Tactic
		public RuleCall getGtacticsTacticParserRuleCall_11_0() { return cGtacticsTacticParserRuleCall_11_0; }
		
		//(',' gtactics+=Tactic)*
		public Group getGroup_12() { return cGroup_12; }
		
		//','
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//gtactics+=Tactic
		public Assignment getGtacticsAssignment_12_1() { return cGtacticsAssignment_12_1; }
		
		//Tactic
		public RuleCall getGtacticsTacticParserRuleCall_12_1_0() { return cGtacticsTacticParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class QScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.QScenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQScenarioAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cQScenarioKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQAKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cQAttributeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cQAttributeQAttributeEnumRuleCall_5_0 = (RuleCall)cQAttributeAssignment_5.eContents().get(0);
		private final Keyword cMeasureKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cMeasureAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cMeasureQAMetricEnumRuleCall_8_0 = (RuleCall)cMeasureAssignment_8.eContents().get(0);
		private final Keyword cMinValueKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMinValueAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMinValueEFloatParserRuleCall_11_0 = (RuleCall)cMinValueAssignment_11.eContents().get(0);
		private final Keyword cMaxValueKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cColonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cMaxValueAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cMaxValueEFloatParserRuleCall_14_0 = (RuleCall)cMaxValueAssignment_14.eContents().get(0);
		private final Keyword cUnitKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cColonKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cUnitAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cUnitMetricUnitEnumRuleCall_17_0 = (RuleCall)cUnitAssignment_17.eContents().get(0);
		private final Keyword cStimulusKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cColonKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cStimulusAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cStimulusEStringParserRuleCall_20_0 = (RuleCall)cStimulusAssignment_20.eContents().get(0);
		private final Keyword cEnvironmentKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Keyword cColonKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Assignment cEnvironmentAssignment_23 = (Assignment)cGroup.eContents().get(23);
		private final RuleCall cEnvironmentEStringParserRuleCall_23_0 = (RuleCall)cEnvironmentAssignment_23.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_24 = (Keyword)cGroup.eContents().get(24);
		
		//QScenario:
		//	{QScenario}
		//	'QScenario'
		//	'{'
		//	'QA' ':' qAttribute=QAttribute
		//	'measure' ':' measure=QAMetric
		//	'minValue' ':' minValue=EFloat
		//	'maxValue' ':' maxValue=EFloat
		//	'unit' ':' unit=MetricUnit
		//	'stimulus' ':' stimulus=EString
		//	'environment' ':' environment=EString
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{QScenario} 'QScenario' '{' 'QA' ':' qAttribute=QAttribute 'measure' ':' measure=QAMetric 'minValue' ':' minValue=EFloat
		//'maxValue' ':' maxValue=EFloat 'unit' ':' unit=MetricUnit 'stimulus' ':' stimulus=EString 'environment' ':'
		//environment=EString '}'
		public Group getGroup() { return cGroup; }
		
		//{QScenario}
		public Action getQScenarioAction_0() { return cQScenarioAction_0; }
		
		//'QScenario'
		public Keyword getQScenarioKeyword_1() { return cQScenarioKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'QA'
		public Keyword getQAKeyword_3() { return cQAKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//qAttribute=QAttribute
		public Assignment getQAttributeAssignment_5() { return cQAttributeAssignment_5; }
		
		//QAttribute
		public RuleCall getQAttributeQAttributeEnumRuleCall_5_0() { return cQAttributeQAttributeEnumRuleCall_5_0; }
		
		//'measure'
		public Keyword getMeasureKeyword_6() { return cMeasureKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//measure=QAMetric
		public Assignment getMeasureAssignment_8() { return cMeasureAssignment_8; }
		
		//QAMetric
		public RuleCall getMeasureQAMetricEnumRuleCall_8_0() { return cMeasureQAMetricEnumRuleCall_8_0; }
		
		//'minValue'
		public Keyword getMinValueKeyword_9() { return cMinValueKeyword_9; }
		
		//':'
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//minValue=EFloat
		public Assignment getMinValueAssignment_11() { return cMinValueAssignment_11; }
		
		//EFloat
		public RuleCall getMinValueEFloatParserRuleCall_11_0() { return cMinValueEFloatParserRuleCall_11_0; }
		
		//'maxValue'
		public Keyword getMaxValueKeyword_12() { return cMaxValueKeyword_12; }
		
		//':'
		public Keyword getColonKeyword_13() { return cColonKeyword_13; }
		
		//maxValue=EFloat
		public Assignment getMaxValueAssignment_14() { return cMaxValueAssignment_14; }
		
		//EFloat
		public RuleCall getMaxValueEFloatParserRuleCall_14_0() { return cMaxValueEFloatParserRuleCall_14_0; }
		
		//'unit'
		public Keyword getUnitKeyword_15() { return cUnitKeyword_15; }
		
		//':'
		public Keyword getColonKeyword_16() { return cColonKeyword_16; }
		
		//unit=MetricUnit
		public Assignment getUnitAssignment_17() { return cUnitAssignment_17; }
		
		//MetricUnit
		public RuleCall getUnitMetricUnitEnumRuleCall_17_0() { return cUnitMetricUnitEnumRuleCall_17_0; }
		
		//'stimulus'
		public Keyword getStimulusKeyword_18() { return cStimulusKeyword_18; }
		
		//':'
		public Keyword getColonKeyword_19() { return cColonKeyword_19; }
		
		//stimulus=EString
		public Assignment getStimulusAssignment_20() { return cStimulusAssignment_20; }
		
		//EString
		public RuleCall getStimulusEStringParserRuleCall_20_0() { return cStimulusEStringParserRuleCall_20_0; }
		
		//'environment'
		public Keyword getEnvironmentKeyword_21() { return cEnvironmentKeyword_21; }
		
		//':'
		public Keyword getColonKeyword_22() { return cColonKeyword_22; }
		
		//environment=EString
		public Assignment getEnvironmentAssignment_23() { return cEnvironmentAssignment_23; }
		
		//EString
		public RuleCall getEnvironmentEStringParserRuleCall_23_0() { return cEnvironmentEStringParserRuleCall_23_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_24() { return cRightCurlyBracketKeyword_24; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat ecore::EFloat:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class AnalyzedQSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.AnalyzedQS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnalyzedQSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cReasoningKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cReasoningAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cReasoningEStringParserRuleCall_2_2_0 = (RuleCall)cReasoningAssignment_2_2.eContents().get(0);
		private final Keyword cQSKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cQsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cQsQScenarioCrossReference_5_0 = (CrossReference)cQsAssignment_5.eContents().get(0);
		private final RuleCall cQsQScenarioEStringParserRuleCall_5_0_1 = (RuleCall)cQsQScenarioCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSPointsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cPointsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cPointsSensitivityPointParserRuleCall_6_2_0 = (RuleCall)cPointsAssignment_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//AnalyzedQS:
		//	'AnalyzedQS'
		//	'{' ('reasoning' ':' reasoning=EString)?
		//	'QS' ':' qs=[QScenario|EString] ('SPoints' '{' points=SensitivityPoint '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'AnalyzedQS' '{' ('reasoning' ':' reasoning=EString)? 'QS' ':' qs=[QScenario|EString] ('SPoints' '{'
		//points=SensitivityPoint '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'AnalyzedQS'
		public Keyword getAnalyzedQSKeyword_0() { return cAnalyzedQSKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('reasoning' ':' reasoning=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'reasoning'
		public Keyword getReasoningKeyword_2_0() { return cReasoningKeyword_2_0; }
		
		//':'
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }
		
		//reasoning=EString
		public Assignment getReasoningAssignment_2_2() { return cReasoningAssignment_2_2; }
		
		//EString
		public RuleCall getReasoningEStringParserRuleCall_2_2_0() { return cReasoningEStringParserRuleCall_2_2_0; }
		
		//'QS'
		public Keyword getQSKeyword_3() { return cQSKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//qs=[QScenario|EString]
		public Assignment getQsAssignment_5() { return cQsAssignment_5; }
		
		//[QScenario|EString]
		public CrossReference getQsQScenarioCrossReference_5_0() { return cQsQScenarioCrossReference_5_0; }
		
		//EString
		public RuleCall getQsQScenarioEStringParserRuleCall_5_0_1() { return cQsQScenarioEStringParserRuleCall_5_0_1; }
		
		//('SPoints' '{' points=SensitivityPoint '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'SPoints'
		public Keyword getSPointsKeyword_6_0() { return cSPointsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//points=SensitivityPoint
		public Assignment getPointsAssignment_6_2() { return cPointsAssignment_6_2; }
		
		//SensitivityPoint
		public RuleCall getPointsSensitivityPointParserRuleCall_6_2_0() { return cPointsSensitivityPointParserRuleCall_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_3() { return cRightCurlyBracketKeyword_6_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class SensitivityPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.SensitivityPoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsRiskAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsRiskIsRiskKeyword_0_0 = (Keyword)cIsRiskAssignment_0.eContents().get(0);
		private final Keyword cSensitivityPointKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRationaleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRationaleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRationaleEStringParserRuleCall_4_1_0 = (RuleCall)cRationaleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCodeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCodeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_5_1_0 = (RuleCall)cCodeAssignment_5_1.eContents().get(0);
		private final Keyword cTacticKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTacticAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cTacticTacticCrossReference_8_0 = (CrossReference)cTacticAssignment_8.eContents().get(0);
		private final RuleCall cTacticTacticEStringParserRuleCall_8_0_1 = (RuleCall)cTacticTacticCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTacticAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cTacticTacticCrossReference_9_1_0 = (CrossReference)cTacticAssignment_9_1.eContents().get(0);
		private final RuleCall cTacticTacticEStringParserRuleCall_9_1_0_1 = (RuleCall)cTacticTacticCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//SensitivityPoint:
		//	isRisk?='isRisk'?
		//	'SensitivityPoint'
		//	name=EString
		//	'{' ('rationale' rationale=EString)? ('code' code=EString)?
		//	'tactic' '(' tactic+=[Tactic|EString] ("," tactic+=[Tactic|EString])* ')'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//isRisk?='isRisk'? 'SensitivityPoint' name=EString '{' ('rationale' rationale=EString)? ('code' code=EString)? 'tactic'
		//'(' tactic+=[Tactic|EString] ("," tactic+=[Tactic|EString])* ')' '}'
		public Group getGroup() { return cGroup; }
		
		//isRisk?='isRisk'?
		public Assignment getIsRiskAssignment_0() { return cIsRiskAssignment_0; }
		
		//'isRisk'
		public Keyword getIsRiskIsRiskKeyword_0_0() { return cIsRiskIsRiskKeyword_0_0; }
		
		//'SensitivityPoint'
		public Keyword getSensitivityPointKeyword_1() { return cSensitivityPointKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('rationale' rationale=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'rationale'
		public Keyword getRationaleKeyword_4_0() { return cRationaleKeyword_4_0; }
		
		//rationale=EString
		public Assignment getRationaleAssignment_4_1() { return cRationaleAssignment_4_1; }
		
		//EString
		public RuleCall getRationaleEStringParserRuleCall_4_1_0() { return cRationaleEStringParserRuleCall_4_1_0; }
		
		//('code' code=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'code'
		public Keyword getCodeKeyword_5_0() { return cCodeKeyword_5_0; }
		
		//code=EString
		public Assignment getCodeAssignment_5_1() { return cCodeAssignment_5_1; }
		
		//EString
		public RuleCall getCodeEStringParserRuleCall_5_1_0() { return cCodeEStringParserRuleCall_5_1_0; }
		
		//'tactic'
		public Keyword getTacticKeyword_6() { return cTacticKeyword_6; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7() { return cLeftParenthesisKeyword_7; }
		
		//tactic+=[Tactic|EString]
		public Assignment getTacticAssignment_8() { return cTacticAssignment_8; }
		
		//[Tactic|EString]
		public CrossReference getTacticTacticCrossReference_8_0() { return cTacticTacticCrossReference_8_0; }
		
		//EString
		public RuleCall getTacticTacticEStringParserRuleCall_8_0_1() { return cTacticTacticEStringParserRuleCall_8_0_1; }
		
		//("," tactic+=[Tactic|EString])*
		public Group getGroup_9() { return cGroup_9; }
		
		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//tactic+=[Tactic|EString]
		public Assignment getTacticAssignment_9_1() { return cTacticAssignment_9_1; }
		
		//[Tactic|EString]
		public CrossReference getTacticTacticCrossReference_9_1_0() { return cTacticTacticCrossReference_9_1_0; }
		
		//EString
		public RuleCall getTacticTacticEStringParserRuleCall_9_1_0_1() { return cTacticTacticEStringParserRuleCall_9_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10() { return cRightParenthesisKeyword_10; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class TacticElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.Tactic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTacticAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTacticKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cQAKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cQAttributeAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cQAttributeQAttributeEnumRuleCall_4_2_0 = (RuleCall)cQAttributeAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRationaleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cColonKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRationaleAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRationaleEStringParserRuleCall_5_2_0 = (RuleCall)cRationaleAssignment_5_2.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cStimulusKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cColonKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cStimulusAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cStimulusEStringParserRuleCall_6_2_0 = (RuleCall)cStimulusAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cResponseKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cColonKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cResponseAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cResponseEStringParserRuleCall_7_2_0 = (RuleCall)cResponseAssignment_7_2.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cViewpointKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cViewpointAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cViewpointEStringParserRuleCall_8_2_0 = (RuleCall)cViewpointAssignment_8_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Tactic:
		//	{Tactic}
		//	'Tactic'
		//	name=EString
		//	'{' ('QA' ':' qAttribute=QAttribute)? ('rationale' ':' rationale=EString)? ('stimulus' ':' stimulus=EString)?
		//	('response' ':' response=EString)? ('viewpoint' ':' viewpoint=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Tactic} 'Tactic' name=EString '{' ('QA' ':' qAttribute=QAttribute)? ('rationale' ':' rationale=EString)? ('stimulus'
		//':' stimulus=EString)? ('response' ':' response=EString)? ('viewpoint' ':' viewpoint=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Tactic}
		public Action getTacticAction_0() { return cTacticAction_0; }
		
		//'Tactic'
		public Keyword getTacticKeyword_1() { return cTacticKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('QA' ':' qAttribute=QAttribute)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'QA'
		public Keyword getQAKeyword_4_0() { return cQAKeyword_4_0; }
		
		//':'
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }
		
		//qAttribute=QAttribute
		public Assignment getQAttributeAssignment_4_2() { return cQAttributeAssignment_4_2; }
		
		//QAttribute
		public RuleCall getQAttributeQAttributeEnumRuleCall_4_2_0() { return cQAttributeQAttributeEnumRuleCall_4_2_0; }
		
		//('rationale' ':' rationale=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'rationale'
		public Keyword getRationaleKeyword_5_0() { return cRationaleKeyword_5_0; }
		
		//':'
		public Keyword getColonKeyword_5_1() { return cColonKeyword_5_1; }
		
		//rationale=EString
		public Assignment getRationaleAssignment_5_2() { return cRationaleAssignment_5_2; }
		
		//EString
		public RuleCall getRationaleEStringParserRuleCall_5_2_0() { return cRationaleEStringParserRuleCall_5_2_0; }
		
		//('stimulus' ':' stimulus=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'stimulus'
		public Keyword getStimulusKeyword_6_0() { return cStimulusKeyword_6_0; }
		
		//':'
		public Keyword getColonKeyword_6_1() { return cColonKeyword_6_1; }
		
		//stimulus=EString
		public Assignment getStimulusAssignment_6_2() { return cStimulusAssignment_6_2; }
		
		//EString
		public RuleCall getStimulusEStringParserRuleCall_6_2_0() { return cStimulusEStringParserRuleCall_6_2_0; }
		
		//('response' ':' response=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'response'
		public Keyword getResponseKeyword_7_0() { return cResponseKeyword_7_0; }
		
		//':'
		public Keyword getColonKeyword_7_1() { return cColonKeyword_7_1; }
		
		//response=EString
		public Assignment getResponseAssignment_7_2() { return cResponseAssignment_7_2; }
		
		//EString
		public RuleCall getResponseEStringParserRuleCall_7_2_0() { return cResponseEStringParserRuleCall_7_2_0; }
		
		//('viewpoint' ':' viewpoint=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'viewpoint'
		public Keyword getViewpointKeyword_8_0() { return cViewpointKeyword_8_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//viewpoint=EString
		public Assignment getViewpointAssignment_8_2() { return cViewpointAssignment_8_2; }
		
		//EString
		public RuleCall getViewpointEStringParserRuleCall_8_2_0() { return cViewpointEStringParserRuleCall_8_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class QAMetricElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.QAMetric");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTHROUGHPUTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTHROUGHPUTTHROUGHPUTKeyword_0_0 = (Keyword)cTHROUGHPUTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLATENCYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLATENCYLATENCYKeyword_1_0 = (Keyword)cLATENCYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDEADLINEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDEADLINEDEADLINEKeyword_2_0 = (Keyword)cDEADLINEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum QAMetric:
		//	THROUGHPUT | LATENCY | DEADLINE;
		public EnumRule getRule() { return rule; }
		
		//THROUGHPUT | LATENCY | DEADLINE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//THROUGHPUT
		public EnumLiteralDeclaration getTHROUGHPUTEnumLiteralDeclaration_0() { return cTHROUGHPUTEnumLiteralDeclaration_0; }
		
		//'THROUGHPUT'
		public Keyword getTHROUGHPUTTHROUGHPUTKeyword_0_0() { return cTHROUGHPUTTHROUGHPUTKeyword_0_0; }
		
		//LATENCY
		public EnumLiteralDeclaration getLATENCYEnumLiteralDeclaration_1() { return cLATENCYEnumLiteralDeclaration_1; }
		
		//'LATENCY'
		public Keyword getLATENCYLATENCYKeyword_1_0() { return cLATENCYLATENCYKeyword_1_0; }
		
		//DEADLINE
		public EnumLiteralDeclaration getDEADLINEEnumLiteralDeclaration_2() { return cDEADLINEEnumLiteralDeclaration_2; }
		
		//'DEADLINE'
		public Keyword getDEADLINEDEADLINEKeyword_2_0() { return cDEADLINEDEADLINEKeyword_2_0; }
	}
	public class MetricUnitElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.MetricUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMILLISEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMILLISMILLISKeyword_0_0 = (Keyword)cMILLISEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSECONDSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSECONDSSECONDSKeyword_1_0 = (Keyword)cSECONDSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMINUTESEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMINUTESMINUTESKeyword_2_0 = (Keyword)cMINUTESEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHOURSEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHOURSHOURSKeyword_3_0 = (Keyword)cHOURSEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTASKSEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTASKSTASKSKeyword_4_0 = (Keyword)cTASKSEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cBYTESEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cBYTESBYTESKeyword_5_0 = (Keyword)cBYTESEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMSGSEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMSGSMSGSKeyword_6_0 = (Keyword)cMSGSEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum MetricUnit:
		//	MILLIS | SECONDS | MINUTES | HOURS | TASKS | BYTES | MSGS;
		public EnumRule getRule() { return rule; }
		
		//MILLIS | SECONDS | MINUTES | HOURS | TASKS | BYTES | MSGS
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MILLIS
		public EnumLiteralDeclaration getMILLISEnumLiteralDeclaration_0() { return cMILLISEnumLiteralDeclaration_0; }
		
		//'MILLIS'
		public Keyword getMILLISMILLISKeyword_0_0() { return cMILLISMILLISKeyword_0_0; }
		
		//SECONDS
		public EnumLiteralDeclaration getSECONDSEnumLiteralDeclaration_1() { return cSECONDSEnumLiteralDeclaration_1; }
		
		//'SECONDS'
		public Keyword getSECONDSSECONDSKeyword_1_0() { return cSECONDSSECONDSKeyword_1_0; }
		
		//MINUTES
		public EnumLiteralDeclaration getMINUTESEnumLiteralDeclaration_2() { return cMINUTESEnumLiteralDeclaration_2; }
		
		//'MINUTES'
		public Keyword getMINUTESMINUTESKeyword_2_0() { return cMINUTESMINUTESKeyword_2_0; }
		
		//HOURS
		public EnumLiteralDeclaration getHOURSEnumLiteralDeclaration_3() { return cHOURSEnumLiteralDeclaration_3; }
		
		//'HOURS'
		public Keyword getHOURSHOURSKeyword_3_0() { return cHOURSHOURSKeyword_3_0; }
		
		//TASKS
		public EnumLiteralDeclaration getTASKSEnumLiteralDeclaration_4() { return cTASKSEnumLiteralDeclaration_4; }
		
		//'TASKS'
		public Keyword getTASKSTASKSKeyword_4_0() { return cTASKSTASKSKeyword_4_0; }
		
		//BYTES
		public EnumLiteralDeclaration getBYTESEnumLiteralDeclaration_5() { return cBYTESEnumLiteralDeclaration_5; }
		
		//'BYTES'
		public Keyword getBYTESBYTESKeyword_5_0() { return cBYTESBYTESKeyword_5_0; }
		
		//MSGS
		public EnumLiteralDeclaration getMSGSEnumLiteralDeclaration_6() { return cMSGSEnumLiteralDeclaration_6; }
		
		//'MSGS'
		public Keyword getMSGSMSGSKeyword_6_0() { return cMSGSMSGSKeyword_6_0; }
	}
	public class QAttributeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.accordant_rq.Ainl.QAttribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAVAILABILITYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAVAILABILITYAVAILABILITYKeyword_0_0 = (Keyword)cAVAILABILITYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPERFORMANCEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPERFORMANCEPERFORMANCEKeyword_1_0 = (Keyword)cPERFORMANCEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMODIFIABILITYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMODIFIABILITYMODIFIABILITYKeyword_2_0 = (Keyword)cMODIFIABILITYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cTESTABILITYEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cTESTABILITYTESTABILITYKeyword_3_0 = (Keyword)cTESTABILITYEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSCALABILITYEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSCALABILITYSCALABILITYKeyword_4_0 = (Keyword)cSCALABILITYEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum QAttribute:
		//	AVAILABILITY | PERFORMANCE | MODIFIABILITY | TESTABILITY | SCALABILITY;
		public EnumRule getRule() { return rule; }
		
		//AVAILABILITY | PERFORMANCE | MODIFIABILITY | TESTABILITY | SCALABILITY
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AVAILABILITY
		public EnumLiteralDeclaration getAVAILABILITYEnumLiteralDeclaration_0() { return cAVAILABILITYEnumLiteralDeclaration_0; }
		
		//'AVAILABILITY'
		public Keyword getAVAILABILITYAVAILABILITYKeyword_0_0() { return cAVAILABILITYAVAILABILITYKeyword_0_0; }
		
		//PERFORMANCE
		public EnumLiteralDeclaration getPERFORMANCEEnumLiteralDeclaration_1() { return cPERFORMANCEEnumLiteralDeclaration_1; }
		
		//'PERFORMANCE'
		public Keyword getPERFORMANCEPERFORMANCEKeyword_1_0() { return cPERFORMANCEPERFORMANCEKeyword_1_0; }
		
		//MODIFIABILITY
		public EnumLiteralDeclaration getMODIFIABILITYEnumLiteralDeclaration_2() { return cMODIFIABILITYEnumLiteralDeclaration_2; }
		
		//'MODIFIABILITY'
		public Keyword getMODIFIABILITYMODIFIABILITYKeyword_2_0() { return cMODIFIABILITYMODIFIABILITYKeyword_2_0; }
		
		//TESTABILITY
		public EnumLiteralDeclaration getTESTABILITYEnumLiteralDeclaration_3() { return cTESTABILITYEnumLiteralDeclaration_3; }
		
		//'TESTABILITY'
		public Keyword getTESTABILITYTESTABILITYKeyword_3_0() { return cTESTABILITYTESTABILITYKeyword_3_0; }
		
		//SCALABILITY
		public EnumLiteralDeclaration getSCALABILITYEnumLiteralDeclaration_4() { return cSCALABILITYEnumLiteralDeclaration_4; }
		
		//'SCALABILITY'
		public Keyword getSCALABILITYSCALABILITYKeyword_4_0() { return cSCALABILITYSCALABILITYKeyword_4_0; }
	}
	
	private final InputPackageElements pInputPackage;
	private final EStringElements pEString;
	private final QScenarioElements pQScenario;
	private final QAMetricElements eQAMetric;
	private final EFloatElements pEFloat;
	private final MetricUnitElements eMetricUnit;
	private final QAttributeElements eQAttribute;
	private final AnalyzedQSElements pAnalyzedQS;
	private final SensitivityPointElements pSensitivityPoint;
	private final TacticElements pTactic;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AinlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pInputPackage = new InputPackageElements();
		this.pEString = new EStringElements();
		this.pQScenario = new QScenarioElements();
		this.eQAMetric = new QAMetricElements();
		this.pEFloat = new EFloatElements();
		this.eMetricUnit = new MetricUnitElements();
		this.eQAttribute = new QAttributeElements();
		this.pAnalyzedQS = new AnalyzedQSElements();
		this.pSensitivityPoint = new SensitivityPointElements();
		this.pTactic = new TacticElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.uniandes.accordant_rq.Ainl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//InputPackage:
	//	{InputPackage}
	//	'InputPackage'
	//	name=EString
	//	'{'
	//	'scenarios' '{' scenarios+=QScenario ("," scenarios+=QScenario)* '}'
	//	'tactics' '{' gtactics+=Tactic (',' gtactics+=Tactic)* '}'
	//	'}';
	public InputPackageElements getInputPackageAccess() {
		return pInputPackage;
	}
	
	public ParserRule getInputPackageRule() {
		return getInputPackageAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//QScenario:
	//	{QScenario}
	//	'QScenario'
	//	'{'
	//	'QA' ':' qAttribute=QAttribute
	//	'measure' ':' measure=QAMetric
	//	'minValue' ':' minValue=EFloat
	//	'maxValue' ':' maxValue=EFloat
	//	'unit' ':' unit=MetricUnit
	//	'stimulus' ':' stimulus=EString
	//	'environment' ':' environment=EString
	//	'}';
	public QScenarioElements getQScenarioAccess() {
		return pQScenario;
	}
	
	public ParserRule getQScenarioRule() {
		return getQScenarioAccess().getRule();
	}
	
	//enum QAMetric:
	//	THROUGHPUT | LATENCY | DEADLINE;
	public QAMetricElements getQAMetricAccess() {
		return eQAMetric;
	}
	
	public EnumRule getQAMetricRule() {
		return getQAMetricAccess().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//enum MetricUnit:
	//	MILLIS | SECONDS | MINUTES | HOURS | TASKS | BYTES | MSGS;
	public MetricUnitElements getMetricUnitAccess() {
		return eMetricUnit;
	}
	
	public EnumRule getMetricUnitRule() {
		return getMetricUnitAccess().getRule();
	}
	
	//enum QAttribute:
	//	AVAILABILITY | PERFORMANCE | MODIFIABILITY | TESTABILITY | SCALABILITY;
	public QAttributeElements getQAttributeAccess() {
		return eQAttribute;
	}
	
	public EnumRule getQAttributeRule() {
		return getQAttributeAccess().getRule();
	}
	
	//AnalyzedQS:
	//	'AnalyzedQS'
	//	'{' ('reasoning' ':' reasoning=EString)?
	//	'QS' ':' qs=[QScenario|EString] ('SPoints' '{' points=SensitivityPoint '}')?
	//	'}';
	public AnalyzedQSElements getAnalyzedQSAccess() {
		return pAnalyzedQS;
	}
	
	public ParserRule getAnalyzedQSRule() {
		return getAnalyzedQSAccess().getRule();
	}
	
	//SensitivityPoint:
	//	isRisk?='isRisk'?
	//	'SensitivityPoint'
	//	name=EString
	//	'{' ('rationale' rationale=EString)? ('code' code=EString)?
	//	'tactic' '(' tactic+=[Tactic|EString] ("," tactic+=[Tactic|EString])* ')'
	//	'}';
	public SensitivityPointElements getSensitivityPointAccess() {
		return pSensitivityPoint;
	}
	
	public ParserRule getSensitivityPointRule() {
		return getSensitivityPointAccess().getRule();
	}
	
	//Tactic:
	//	{Tactic}
	//	'Tactic'
	//	name=EString
	//	'{' ('QA' ':' qAttribute=QAttribute)? ('rationale' ':' rationale=EString)? ('stimulus' ':' stimulus=EString)?
	//	('response' ':' response=EString)? ('viewpoint' ':' viewpoint=EString)?
	//	'}';
	public TacticElements getTacticAccess() {
		return pTactic;
	}
	
	public ParserRule getTacticRule() {
		return getTacticAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
