/*
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_dv.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.accordant.dv.ui.internal.DvActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AdvlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DvActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DvActivator activator = DvActivator.getInstance();
		return activator != null ? activator.getInjector(DvActivator.CO_EDU_UNIANDES_ACCORDANT_DV_ADVL) : null;
	}

}
