/**
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_rq.serializer;

import co.edu.uniandes.accordant_rq.serializer.AbstractAinlSyntacticSequencer;

@SuppressWarnings("all")
public class AinlSyntacticSequencer extends AbstractAinlSyntacticSequencer {
}
