<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="accordant_rq" nsURI="http://uniandes.accordant.requirement"
    nsPrefix="accordant_rq">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        upperBound="-1" eType="#//QScenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tactics" upperBound="-1"
        eType="#//Tactic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedQs" upperBound="-1"
        eType="#//AnalyzedQS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QAMetric">
    <eLiterals name="THROUGHPUT" literal="THROUGHPUT"/>
    <eLiterals name="LATENCY" value="1"/>
    <eLiterals name="DEADLINE" value="3"/>
    <eLiterals name="UPDATETIME" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MetricUnit">
    <eLiterals name="MILLIS"/>
    <eLiterals name="SECONDS" value="1"/>
    <eLiterals name="MINUTES" value="2"/>
    <eLiterals name="HOURS" value="3"/>
    <eLiterals name="TASKS" value="4"/>
    <eLiterals name="BYTES" value="5"/>
    <eLiterals name="MSGS" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QScenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure" lowerBound="1"
        eType="#//QAMetric"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//MetricUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qAttribute" lowerBound="1"
        eType="#//QAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stimulus" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="response" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchDecision">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedTactics" upperBound="-1"
        eType="#//Tactic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRisk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSensitivityPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tactic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qAttribute" eType="#//QAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stimulus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="response" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QAttribute">
    <eLiterals name="AVAILABILITY" literal="AVAILABILITY"/>
    <eLiterals name="PERFORMANCE" value="1"/>
    <eLiterals name="MODIFIABILITY" value="2"/>
    <eLiterals name="TESTABILITY" value="3"/>
    <eLiterals name="SCALABILITY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalyzedQS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisions" eType="#//ArchDecision"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qs" lowerBound="1" eType="#//QScenario"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reasoning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ConstraintType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintType">
    <eLiterals name="CLOUD_PROV"/>
    <eLiterals name="PROC_MODEL" value="1"/>
    <eLiterals name="LICENSE" value="2"/>
    <eLiterals name="TECH_VENDOR" value="3"/>
    <eLiterals name="ARCH_STYLE" value="4"/>
  </eClassifiers>
</ecore:EPackage>
