/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.accordant_fv.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAfvlScopeProvider extends DelegatingScopeProvider {
}
