/*
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_dv.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.accordant.dv.ui.internal.DvActivator;

public class AdvlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DvActivator.getInstance().getInjector("co.edu.uniandes.accordant_dv.Advl");
	}

}
