/*
 * generated by Xtext 2.18.0.M3
 */
package co.edu.uniandes.accordant_rq.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.accordant.rq.ui.internal.RqActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AinlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RqActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RqActivator activator = RqActivator.getInstance();
		return activator != null ? activator.getInjector(RqActivator.CO_EDU_UNIANDES_ACCORDANT_RQ_AINL) : null;
	}

}
